# Generated by Django 2.2.6 on 2019-12-12 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dataExpira',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 2, 37, 792947)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataReserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 12, 14, 2, 37, 792920)),
        ),
    ]
