# Generated by Django 2.2.6 on 2019-12-12 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20191212_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dataExpira',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 17, 11, 43, 150)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataReserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 12, 17, 11, 43, 123)),
        ),
    ]
