# Generated by Django 2.2.6 on 2019-12-16 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_auto_20191212_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dataExpira',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 23, 13, 16, 37, 120179)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataReserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 16, 13, 16, 37, 120151)),
        ),
    ]
