# Generated by Django 2.2.6 on 2019-12-16 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20191212_1711'),
        ('reserva', '0005_auto_20191216_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='biblioteca',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='livro',
        ),
        migrations.AddField(
            model_name='reserva',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataExpira',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 23, 22, 42, 42, 596933)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataReserva',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 16, 22, 42, 42, 596900)),
        ),
    ]
