# Generated by Django 2.2.6 on 2019-12-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(default='Minas Gerais', max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'unique_together': {('nome', 'usuario')},
            },
        ),
    ]
