# Generated by Django 2.2.6 on 2019-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('subarea', models.CharField(max_length=50)),
                ('anoPublicacao', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('edicao', models.IntegerField(null=True)),
                ('autor', models.ManyToManyField(to='autor.Autor')),
            ],
        ),
    ]
