# Generated by Django 2.2.6 on 2019-11-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('subarea', models.CharField(max_length=50)),
                ('anoPublicacao', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('edicao', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autor.Autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.Livro')),
            ],
        ),
    ]
