# Generated by Django 2.2.6 on 2019-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('CPF', models.CharField(default='teste', max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(default='Minas Gerais', max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1, null=True)),
                ('tipo', models.CharField(choices=[('L', 'Leitor'), ('D', 'Dono'), ('B', 'Bibliotecário')], default='L', max_length=1)),
            ],
        ),
    ]
