# Generated by Django 2.2.6 on 2019-11-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
            ],
        ),
    ]
