# Generated by Django 2.2.6 on 2019-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
