# Generated by Django 2.2.6 on 2019-11-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20191126_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='equipe',
            new_name='is_staff',
        ),
    ]
