# Generated by Django 2.2.6 on 2019-11-28 12:55

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20191126_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ativado',
            field=models.BooleanField(default=True, help_text='Designa se este usuário deveria ser tratado como ativo. Desmarca ele ao invés de excluir contas.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designa se o usuário pode logar nesta área de administrador.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='teste', help_text='Requerido. 15 caracteres ou menos. Letras, números e  @/./+/-/_', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Insira um nome de usuário válido.', 'inválido')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='validado',
            field=models.BooleanField(default=False, help_text='Designa se este usuário confirmou a sua conta.', verbose_name='trusty'),
        ),
    ]
