# Generated by Django 2.2.6 on 2019-12-12 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 12, 14, 2, 37, 791759)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataPreDev',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 2, 37, 791799)),
        ),
    ]
