# Generated by Django 2.2.6 on 2019-12-16 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0005_auto_20191216_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 16, 22, 42, 42, 594192)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataPreDev',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 23, 22, 42, 42, 594223)),
        ),
    ]
