# Generated by Django 2.2.6 on 2019-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dataNascimento', models.DateField(null=True)),
            ],
        ),
    ]
